---
- name: Firewall Configuration for all servers
  hosts: all  
  become: yes
  roles:
    - firewall

- hosts: app_server
  become: yes
  roles:
    - docker

- hosts: nginx_server
  become: yes
  roles:
    - nginx
    